# Generated by Django 5.1.3 on 2025-04-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabularModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_description', models.CharField(max_length=200)),
                ('template_name', models.CharField(max_length=200)),
            ],
        ),
    ]
