# Generated by Django 5.1.3 on 2025-04-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0002_tabularmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDecriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_description', models.CharField(max_length=150)),
                ('developed_by', models.CharField(max_length=200)),
                ('uses', models.CharField(blank=True, max_length=300)),
                ('bias_and_risks', models.CharField(blank=True, max_length=300)),
                ('recommendations', models.CharField(blank=True, max_length=500)),
                ('metrics', models.CharField(blank=True, max_length=200)),
                ('results', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
            ],
        ),
    ]
