# Generated by Django 5.1.3 on 2025-04-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0003_modeldecriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldecriptions',
            name='id',
        ),
        migrations.AddField(
            model_name='modeldecriptions',
            name='model_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
