# Generated by Django 5.2.1 on 2025-05-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0004_remove_modeldecriptions_id_modeldecriptions_model_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.JSONField()),
            ],
        ),
    ]
