# Generated by Django 5.2.1 on 2025-06-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0005_userpostdocumentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='neural/media')),
            ],
        ),
    ]
