# Generated by Django 5.2.1 on 2025-06-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0006_userimagepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimagepost',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
    ]
