# Generated by Django 5.2.1 on 2025-06-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0007_alter_userimagepost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImagePostPneumonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='neural/Pneumonia')),
            ],
        ),
        migrations.AlterField(
            model_name='userimagepost',
            name='image',
            field=models.ImageField(upload_to='neural/media'),
        ),
    ]
