# Generated by Django 5.2.1 on 2025-06-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0008_userimagepostpneumonia_alter_userimagepost_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImagePost',
        ),
        migrations.DeleteModel(
            name='UserImagePostPneumonia',
        ),
    ]
