# Generated by Django 5.2.1 on 2025-06-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0011_userimagepostpneumonia_alter_userimagepost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.JSONField()),
            ],
        ),
    ]
