# Generated by Django 5.2.1 on 2025-06-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0013_userlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='userlist',
            name='email',
            field=models.EmailField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
