# Generated by Django 5.2.1 on 2025-06-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0014_remove_userlist_id_alter_userlist_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
