# Generated by Django 5.2.1 on 2025-06-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0015_userlist_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_descr', models.CharField(max_length=200)),
                ('href_name', models.CharField(max_length=30)),
            ],
        ),
    ]
