# Generated by Django 5.2.1 on 2025-06-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0016_productlistcards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductListCards',
        ),
    ]
