# Generated by Django 5.2.1 on 2025-07-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural', '0019_chartfileuploaderdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartfileuploaderdata',
            name='categorical_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chartfileuploaderdata',
            name='data_label_numeric',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chartfileuploaderdata',
            name='data_numeric',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
